#version 430 core



layout(std430, binding = 12) buffer rayBucketsBuffer{
    uint buckets[256];
};

layout (local_size_x = 32, local_size_y = 1) in;

void main(){
    
    uint tid = gl_GlobalInvocationID.x;

    if(tid > 0)
        return;

    uint totalCount = 0;
    for(int i = 0; i < 256; i ++){
        uint count = buckets[i];
        buckets[i] = totalCount;
        totalCount += count;
    }

}

